"""Run during Docker build to pre-build the ChromaDB index."""
import json
from pathlib import Path
from utils import create_and_persist_vectorstore

DOCS = Path("./documents")

pdf_paths = [str(p) for p in DOCS.glob("*.pdf")]
if not pdf_paths:
    raise RuntimeError("No PDFs found in documents/")

# Load Groq Vision descriptions if available (generated by preprocess_vision.py)
vision_descriptions = None
vision_path = DOCS / "vision_descriptions.json"
if vision_path.exists():
    with open(vision_path, encoding="utf-8") as f:
        vision_descriptions = json.load(f)
    print(f"Vision descriptions loaded for: {list(vision_descriptions.keys())}")
else:
    print("No vision_descriptions.json found — indexing text only.")

_, index_name = create_and_persist_vectorstore(
    embedding_model_name="sentence-transformers/all-MiniLM-L6-v2",
    pdf_paths=pdf_paths,
    chunk_size=1000,
    chunk_tag="cloud",
    tags_for_metadata=["general"],
    collection_name_prefix="rag_docs",
    pdf_folder_path="documents",
    include_image_descriptions=False,
    visualize_chunks=False,
    vision_descriptions=vision_descriptions,
)
Path("last_index.txt").write_text(index_name)
print("Index built:", index_name)
